import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useMemo, useState } from 'react'
import Body from '../components/layouts/Body'
import Theme from '../components/layouts/Theme'
import Box from '../components/molecules/Box'
import { TUserEducation } from '../utils'

const Home: NextPage = () => {
  const ISSERVER = typeof window === "undefined";
  const [userName, setUserName] = useState<undefined | string>();
  const [userEducation, setUserEducation] = useState<Array<TUserEducation>>([]);

  useEffect(() => {
    if (!ISSERVER) {
      const userNameFromLocalStorage = localStorage.getItem('userName');
      if (userNameFromLocalStorage) {
        setUserName(userNameFromLocalStorage);
      }
      const userEducationFromLocalStorage = localStorage.getItem('userEducation');
      if(userEducationFromLocalStorage) {
        const parsedUserEducation = JSON.parse(userEducationFromLocalStorage);
        setUserEducation(parsedUserEducation);
      }
    }
  }, [ISSERVER]);

  const onEntername = (name: string) => {
    setUserName(name);
    localStorage.setItem('userName', name);
  }

  return (
    <div>
      <Head>
        <title>Showwcase Education</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Box
        color='text'
        bg='background'
        minHeight='100vh'
        width='100%'
        position='relative'>
        <Theme />
        <Body userName={userName} userEducation={userEducation} onEntername={onEntername} setUserEducation={setUserEducation} />
      </Box>
    </div>
  )
}

export default Home
