import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import Body from '../components/layouts/Body'
import Theme from '../components/layouts/Theme'
import Box from '../components/molecules/Box'

const Home: NextPage = () => {
  const ISSERVER = typeof window === "undefined";
  const [userName, setUserName] = useState<undefined | string>();
  useEffect(() => {
    if (!ISSERVER) {
      const userNameFromLocalStorage = localStorage.getItem('userName');
      if (userNameFromLocalStorage) {
        setUserName(userNameFromLocalStorage);
      }
    }
  }, [ISSERVER]);

  const onEntername = (name: string) => {
    setUserName(name);
    localStorage.setItem('userName', name);
  }

  return (
    <div>
      <Head>
        <title>Showwcase Education</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Box
        color='text'
        bg='background'
        minHeight='100vh'
        w='100%'
        position='relative'>
        <Theme />
        <Body userName={userName} onEntername={onEntername} />
      </Box>
    </div>
  )
}

export default Home
